#!/usr/bin/env bash
# This script will change your home IP address to the one you provide

sudo sed -i.bak -e 's/^\s*127\.0\.0\.1\s\+localhost/127.0.0.2 localhost/' -e '/facebook\.com/d' /etc/hosts && echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
